# Generated by Django 2.0.3 on 2018-03-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College', models.CharField(max_length=250)),
                ('Photo', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=250)),
                ('phone', models.IntegerField(max_length=12)),
                ('linkedin', models.URLField(max_length=100)),
                ('github', models.URLField(max_length=100)),
            ],
        ),
    ]
