# Generated by Django 2.0.3 on 2018-03-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('First_name', models.CharField(default='', max_length=100)),
                ('Middle_name', models.CharField(default='', max_length=100)),
                ('Last_name', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(default='', max_length=250, primary_key=True, serialize=False)),
                ('DOB', models.DateField(default='', null=True)),
                ('phone', models.IntegerField()),
                ('linkedin', models.URLField(max_length=100)),
                ('github', models.URLField(max_length=100)),
            ],
        ),
    ]
