# Generated by Django 2.0.3 on 2018-03-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='github',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='name',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
