# Generated by Django 2.0.3 on 2018-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
