# Generated by Django 2.0.3 on 2018-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180330_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='Photo',
            field=models.ImageField(null=True, upload_to='user/Image/'),
        ),
    ]
