# Generated by Django 2.0.3 on 2018-03-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180318_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='Photo',
        ),
    ]
