# Generated by Django 2.0.3 on 2018-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_name_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='id',
        ),
        migrations.AlterField(
            model_name='name',
            name='Email',
            field=models.EmailField(default='', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
