# Generated by Django 2.0.5 on 2018-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20180330_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='name',
            name='Email',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
